# Default values for dxemssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General
# CAUTION: Setting the replica quantity to a value less than 3 does not meet Microsoft's quorum requirements for HA. 
# See https://support.dh2i.com/docs/kbs/sql_server/availability_groups/quorum-considerations-for-sql-server-availability-groups
# Only set this value below 3 if you intend to assign these replicas to an existing availability group
replicas: 3
secretKeys: null
mssqlSecret: null
enableLoadBalancers: true
serviceAccount: null

# SQL Server settings
sqlImage:
  repository: "mcr.microsoft.com/mssql/server"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2022-latest"
  volumeClaimConfiguration: null
    #the chart will assume the values below if volumeClaimConfiguration: null
    #storageClassName: <Kubernetes default>
    #resources:
    #  requests:
    #    storage: 8Gi

  env:
    MSSQL_PID: "Developer"
    ACCEPT_EULA: false
    MSSQL_AGENT_ENABLED: false

# DxEnterprise settings
dxeImage:
  repository: docker.io/dh2i/dxe
  pullPolicy: Always
  tag: latest
  volumeClaimConfiguration: null
    #the chart will assume the values below if volumeClaimConfiguration: null
    #storageClassName: <Kubernetes default>
    #resources:
    #  requests:
    #    storage: 1Gi
  env:
    DX_ACCEPT_EULA: false
    DX_VHOST_NAME: "VHOST1"
    DX_AG_NAME: "AG1"
    DX_AG_OPTIONS: ""
    DX_NEW_CLUSTER: true
    DX_USE_NAT: false
    DX_JOIN_TARGET: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
hostAliases: []
dnsConfig: {}
