apiVersion: v2
kubeVersion: ">= 1.20.0"
name: dxemssql-combined
description: "Helm chart for DH2i's DxEnterprise image combined with SQL Server availability groups"
type: application
appVersion: "22.0"
version: "1.0.3"
icon: https://raw.githubusercontent.com/dh2i/helm/main/assets/DH2i_Logo_Icon.png
annotations:
  catalog.cattle.io/display-name: "DH2i SQL Server Combined Image"
  charts.openshift.io/name: "DH2i SQL Server Combined Image"
