# Default values for dxemssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General
# CAUTION: Setting the replica quantity to a value less than 3 does not meet Microsoft's quorum requirements for HA. 
# See https://support.dh2i.com/docs/kbs/sql_server/availability_groups/quorum-considerations-for-sql-server-availability-groups
# Only set this value below 3 if you intend to assign these replicas to an existing availability group
replicas: 3
secretKeys: null
mssqlSecret: null
enableLoadBalancers: true
serviceAccount: null

# DxEnterprise settings
# See https://support.dh2i.com/docs/v22.0/guides/dxenterprise/containers/building-dxemssql-qsg for building an image
repository: null
pullPolicy: Always
tag: latest
env:
  # SQL Server settings
  ACCEPT_EULA: false
  MSSQL_AGENT_ENABLED: false
  MSSQL_PID: "Developer"
  # DxEnterprise settings
  DX_ACCEPT_EULA: false
  DX_VHOST_NAME: "VHOST1"
  DX_AG_NAME: "AG1"
  DX_AG_OPTIONS: ""
  DX_NEW_CLUSTER: true
  DX_USE_NAT: false
  DX_JOIN_TARGET: ""

nameOverride: ""
fullnameOverride: ""

sqlVolumeClaimConfiguration: null
  #the chart will assume the values below if sqlVolumeClaimConfiguration: null
  #storageClassName: <Kubernetes default>
  #resources:
  #  requests:
  #    storage: 8Gi
dxeVolumeClaimConfiguration: null
  #the chart will assume the values below if dxeVolumeClaimConfiguration: null
  #storageClassName: <Kubernetes default>
  #resources:
  #  requests:
  #    storage: 1Gi
podAnnotations: {}
hostAliases: []
dnsConfig: {}
